"""
Documentation Generator Configuration & Options.
Controls modular chapter composition, details to include, and RAG optimization flags.
Vanilla Python implementation.
"""

import json
import os
import re
from dataclasses import dataclass, field, asdict
from typing import List, Set, Optional, Dict, Any, Tuple


@dataclass
class DocGenConfig:
    # Table exclusion filters (e.g. auto date/time tables generated by Power BI)
    exclude_auto_date_tables: bool = True
    excluded_table_patterns: List[str] = field(
        default_factory=lambda: [
            r"^LocalDateTable_.*",
            r"^DateTableTemplate_.*",
            r"^LocalDateTable\b.*",
        ]
    )
    excluded_tables: List[str] = field(default_factory=list)

    # Inherited Entities publication filter (partition = entity and EXTERNALMEASURE)
    include_inherited_entities: bool = False

    # Table documentation modular sections
    include_table_yaml_frontmatter: bool = True
    include_table_topology_section: bool = True
    include_table_lineage_section: bool = True
    include_table_incremental_refresh: bool = True
    include_table_columns_dictionary: bool = True
    include_table_relationships_section: bool = True
    include_table_snowflake_paths: bool = True
    include_table_measures_list: bool = True
    include_table_m_code: bool = True
    include_table_rag_hints: bool = True

    # Measure documentation modular sections
    include_measure_yaml_frontmatter: bool = True
    include_measure_dax_formula: bool = True
    include_measure_upstream_deps: bool = True
    include_measure_downstream_impact: bool = True
    include_measure_referenced_columns: bool = True
    include_measure_rag_hints: bool = True

    # Function documentation modular sections
    include_function_yaml_frontmatter: bool = True
    include_function_parameters_section: bool = True
    include_function_formula_section: bool = True
    include_function_downstream_section: bool = True
    include_function_rag_hints: bool = True

    # Expression / Shared Query documentation modular sections
    include_expression_docs: bool = True
    include_expression_yaml_frontmatter: bool = True
    include_expression_overview_section: bool = True
    include_expression_inline_table: bool = True
    include_expression_lineage_section: bool = True
    include_expression_steps_section: bool = True
    include_expression_m_code: bool = True
    include_expression_rag_hints: bool = True

    # General options
    output_dir: str = "docs"
    tables_subdir: str = "tables"
    measures_subdir: str = "measures"
    functions_subdir: str = "functions"
    expressions_subdir: str = "expressions"
    generate_index_file: bool = True
    sanitize_filenames: bool = True
    include_markdown_links: bool = True  # Cross-link measures to tables and vice-versa

    def is_table_excluded(self, table_name: Optional[str]) -> bool:
        """
        Returns True if the given table name matches any explicit exclusion
        or auto-generated date pattern (e.g. LocalDateTable_*, DateTableTemplate_*).
        """
        if not table_name:
            return False
        
        name_clean = str(table_name).strip()

        # Check explicit table list
        if name_clean in self.excluded_tables:
            return True

        # Check regex patterns if auto table exclusion is active
        if self.exclude_auto_date_tables:
            for pattern in self.excluded_table_patterns:
                try:
                    if re.search(pattern, name_clean, re.IGNORECASE):
                        return True
                except re.error:
                    if pattern.lower() in name_clean.lower():
                        return True

        return False

    def is_table_published(self, table_data: Optional[Dict[str, Any]]) -> bool:
        """
        Returns True if a dedicated Markdown document should be published for this table.
        Inherited tables (partition = entity) are not published when include_inherited_entities is False.
        """
        if not table_data:
            return False
        if self.is_table_excluded(table_data.get("name")):
            return False
        if not self.include_inherited_entities and (table_data.get("is_inherited") or table_data.get("out_of_scope")):
            return False
        return True

    def is_measure_published(self, measure_data: Optional[Dict[str, Any]]) -> bool:
        """
        Returns True if a dedicated Markdown document should be published for this measure.
        External measures (EXTERNALMEASURE) are not published when include_inherited_entities is False.
        """
        if not measure_data:
            return False
        if self.is_table_excluded(measure_data.get("table")):
            return False
        if not self.include_inherited_entities and (
            measure_data.get("is_inherited")
            or measure_data.get("is_external_measure")
            or measure_data.get("out_of_scope")
        ):
            return False
        return True

    @classmethod
    def load_from_file(cls, filepath: str) -> "DocGenConfig":
        """Loads configuration from a JSON file, overriding defaults."""
        if not os.path.exists(filepath):
            return cls()
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            # Filter keys to match dataclass fields
            valid_keys = {f.name for f in cls.__dataclass_fields__.values()}
            filtered = {k: v for k, v in data.items() if k in valid_keys}
            return cls(**filtered)
        except Exception as e:
            print(f"[WARNING] Failed to load config from '{filepath}': {e}. Using defaults.")
            return cls()

    @classmethod
    def find_and_load_default(cls, base_dir: Optional[str] = None) -> "DocGenConfig":
        """Searches for pbip_doc.config.json in current directory or target path."""
        candidates = ["pbip_doc.config.json", "pbip_doc_config.json", ".pbip_doc.json"]
        if base_dir:
            candidates.insert(0, os.path.join(base_dir, "pbip_doc.config.json"))
        
        for cand in candidates:
            if os.path.exists(cand):
                return cls.load_from_file(cand)
        return cls()

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        """Serializes current configuration to formatted JSON string."""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)

    def apply_overrides(self, overrides: Dict[str, Any]) -> None:
        """
        Applies a dictionary of configuration overrides with automatic type coercion.
        Ignores keys that do not correspond to valid DocGenConfig fields.
        """
        valid_fields = self.__dataclass_fields__
        for key, val in overrides.items():
            if key in valid_fields:
                current_val = getattr(self, key)
                coerced = self._coerce_value(current_val, val)
                setattr(self, key, coerced)

    @classmethod
    def _coerce_value(cls, current_val: Any, new_val: Any) -> Any:
        if isinstance(current_val, bool):
            if isinstance(new_val, bool):
                return new_val
            if isinstance(new_val, str):
                lower = new_val.strip().lower()
                if lower in ("true", "1", "yes", "on", "t"):
                    return True
                if lower in ("false", "0", "no", "off", "f"):
                    return False
            return bool(new_val)
        elif isinstance(current_val, int) and not isinstance(current_val, bool):
            try:
                return int(new_val)
            except (ValueError, TypeError):
                return current_val
        elif isinstance(current_val, list):
            if isinstance(new_val, list):
                return new_val
            if isinstance(new_val, str):
                clean = new_val.strip()
                if clean.startswith("[") and clean.endswith("]"):
                    try:
                        parsed = json.loads(clean)
                        if isinstance(parsed, list):
                            return parsed
                    except Exception:
                        pass
                return [item.strip() for item in clean.split(",") if item.strip()]
            return [new_val]
        elif isinstance(current_val, str):
            return str(new_val)
        return new_val

    @classmethod
    def parse_set_arg(cls, set_expr: str) -> Tuple[str, str]:
        """Parses a 'key=value' CLI argument into a (key, raw_value) tuple."""
        if "=" not in set_expr:
            raise ValueError(f"Invalid --set expression '{set_expr}'. Expected format: key=value")
        key, val = set_expr.split("=", 1)
        return key.strip(), val.strip()

    @classmethod
    def get_template_dict(cls) -> Dict[str, Any]:
        """Returns a comprehensive dictionary with all available configuration keys, defaults, and descriptions."""
        instance = cls()
        data = asdict(instance)
        template: Dict[str, Any] = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "title": "pbip-doc-skill Configuration",
            "description": "Configuration settings for PBIP model parsing and documentation generation.",
        }
        template.update(data)
        return template

    @classmethod
    def get_descriptions(cls) -> Dict[str, str]:
        """Returns human-readable descriptions for all configuration parameters."""
        return {
            "exclude_auto_date_tables": "Exclude Power BI auto-generated date tables (LocalDateTable_*, DateTableTemplate_*).",
            "excluded_table_patterns": "List of regex patterns for table names to exclude from documentation.",
            "excluded_tables": "List of explicit table names to exclude.",
            "include_inherited_entities": "Whether to publish documentation for inherited entities (partition = entity) and external measures.",
            "include_table_yaml_frontmatter": "Include structured YAML frontmatter at top of table docs.",
            "include_table_topology_section": "Include Star Schema topology role and classification section in table docs.",
            "include_table_lineage_section": "Include Power Query M data lineage section in table docs.",
            "include_table_incremental_refresh": "Include incremental refresh policy details in table docs.",
            "include_table_columns_dictionary": "Include column data dictionary table in table docs.",
            "include_table_relationships_section": "Include incoming and outgoing relationships in table docs.",
            "include_table_snowflake_paths": "Include recursive snowflake outrigger paths in table docs.",
            "include_table_measures_list": "Include table measures summary list in table docs.",
            "include_table_m_code": "Include raw Power Query M code block in table docs.",
            "include_table_rag_hints": "Include contextual RAG search questions and hints in table docs.",
            "include_measure_yaml_frontmatter": "Include structured YAML frontmatter at top of measure docs.",
            "include_measure_dax_formula": "Include formatted DAX code block in measure docs.",
            "include_measure_upstream_deps": "Include upstream measure dependencies and calculation depth in measure docs.",
            "include_measure_downstream_impact": "Include downstream impacted measures list in measure docs.",
            "include_measure_referenced_columns": "Include referenced columns list in measure docs.",
            "include_measure_rag_hints": "Include contextual RAG search hints in measure docs.",
            "include_function_yaml_frontmatter": "Include YAML frontmatter at top of DAX UDF function docs.",
            "include_function_parameters_section": "Include parameter signatures in function docs.",
            "include_function_formula_section": "Include DAX formula in function docs.",
            "include_function_downstream_section": "Include downstream dependent measures in function docs.",
            "include_function_rag_hints": "Include contextual RAG hints in function docs.",
            "include_expression_docs": "Generate standalone documentation for shared M queries and parameters.",
            "include_expression_yaml_frontmatter": "Include YAML frontmatter at top of expression docs.",
            "include_expression_overview_section": "Include expression summary in expression docs.",
            "include_expression_inline_table": "Parse and render #table inline data rows in expression docs.",
            "include_expression_lineage_section": "Include data source connection details in expression docs.",
            "include_expression_steps_section": "Include step-by-step transformation breakdown in expression docs.",
            "include_expression_m_code": "Include raw M code in expression docs.",
            "include_expression_rag_hints": "Include contextual RAG hints in expression docs.",
            "output_dir": "Target directory where documentation files are written.",
            "tables_subdir": "Subdirectory name for table documentation pages.",
            "measures_subdir": "Subdirectory name for measure documentation pages.",
            "functions_subdir": "Subdirectory name for DAX UDF function documentation pages.",
            "expressions_subdir": "Subdirectory name for shared query / expression documentation pages.",
            "generate_index_file": "Generate master INDEX.md catalog.",
            "sanitize_filenames": "Sanitize special characters in generated markdown filenames.",
            "include_markdown_links": "Render cross-links between measures and tables in generated markdown.",
        }
