table DimGeography
	lineageTag: c2d3e4f5-a6b7-8c9d-0e1f-2a3b4c5d6e7f

	column GeographyKey
		dataType: int64
		isKey
		summarizeBy: none
		sourceColumn: GeographyKey

	column City
		dataType: string
		summarizeBy: none
		sourceColumn: City

	column StateProvince
		dataType: string
		summarizeBy: none
		sourceColumn: StateProvince

	column CountryKey
		dataType: int64
		summarizeBy: none
		sourceColumn: CountryKey

	partition DimGeography = m
		mode: import
		source =
			let
				Source = #"Staging Geography",
				#"Filtered Rows" = Table.SelectRows(Source, each [GeographyKey] <> null)
			in
				#"Filtered Rows"
